Added Customizable Name Field from User Mapping
davidpesce/moodle-logstore_xapi pull request #125
Opened 2017-07-14 18:26 UTC by ericbram

Added a UI configuration that allows users to replace the xAPI
Actor->Account->Name field with a mapping other than the user's Moodle
Id.

2017-07-17 13:55 UTC, ryansmith94 commented
Hey @ericbram, unfortunately we can't merge this until the Travis build passes, [it's failing right now](https://travis-ci.org/xAPI-vle/moodle-logstore_xapi/builds/253717162?utm_source=github_status&utm_medium=notification).

```
PHP Fatal error:  Undefined class constant 'AUTHSYNCFIELDS' in /home/travis/build/moodle/admin/tool/log/store/xapi/settings.php on line 33
```

2017-07-17 13:57 UTC, ryasmi requested changes

2017-07-17 13:57 UTC, ryansmith94 commented on lib/translator/src/Events/Event.php
> +		$subField = get_config('logstore_xapi', 'account') ?: 'id';
For testing purposes, the `get_config` function should not be used in the Translator. Pass this through the constructor instead.

2017-07-17 13:57 UTC, ryansmith94 commented on settings.php
> +	$accountOpts = array_merge(['id'], \core_user::AUTHSYNCFIELDS);
Assuming something is wrong here since attempting to use `AUTHSYNCFIELDS` throws an error.

2017-07-17 14:11 UTC, ericbram commented
Thanks for taking a look at this, I am not familiar with contributing to other projects yet and actually thought I was still merging to my forked version!  I'll have to take a look at the AUTHSYNCFIELDS error when I get a chance, that code seemed to have been working fine for me locally.

2017-07-17 14:36 UTC, ryansmith94 commented
You're welcome @ericbram 👍 Haha no worries. Okay thank you, yeah that doesn't surprise me, it'll just be because Moodle isn't technically running during that build. We have to keep our tests quite isolated.

2017-07-17 15:55 UTC, ericbram commented
Understood!  I was trying to re-use that list of user mapping options and that seemed to be the only array list.  I'll see if I can find a way to make that accessible or if I have to re-create that list.

2017-07-18 11:30 UTC, ryansmith94 commented
Okay nice :smile:

2018-01-03 14:58 UTC, bseclier commented
Hi,
Any news about this PR ? We are currently looking for this feature too (we'll patch our code locally by now, but it would be nice adding this feature in the official source code).
Thanks,

2018-01-03 15:04 UTC, ericbram commented
Hi,

Unfortunately I had to move on as I was doing that at the request of my
company and they have since shifted priorities.  Feel free to use any of
the code I had written to complete the PR as necessary.  If I remember
right, I was just trying to avoid re-implementing an ENUM which was causing
the issue.


Thanks,
Eric Bram

On Wed, Jan 3, 2018 at 9:58 AM, Benjamin SECLIER <notifications@github.com>
wrote:

> Hi,
> Any news about this PR ? We are currently looking for this feature too
> (we'll patch our code locally by now, but it would be nice adding this
> feature in the official source code).
> Thanks,
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xAPI-vle/moodle-logstore_xapi/pull/125#issuecomment-355032207>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGnV0xJmiQIraSXqofCpx7RPQw7LYO8Vks5tG5WbgaJpZM4OYlNE>
> .
>

2018-07-06 09:09 UTC, ryansmith94 commented
Closing due to inactivity.

2018-07-06 09:09 UTC, closed without merging