feat: Adds statement for numeric feedback questions.
davidpesce/moodle-logstore_xapi pull request #215
Opened 2018-08-02 10:51 UTC by ryansmith94

2018-08-02 13:00 UTC, Ian247 requested changes
Add response numeric value into extensions.

2018-08-02 13:03 UTC, ryansmith94 commented
@Ian247 updated.

2018-08-02 13:53 UTC, Ian247 submitted a review, later dismissed

2018-08-03 08:40 UTC, Ian247 approved these changes

2018-08-03 08:54 UTC, merged