Lms 3030
davidpesce/moodle-logstore_xapi pull request #770
Opened 2020-08-06 17:34 UTC by Patches-

**Description**
- LMS-3029 & LMS-3030 - Hiding historic log results and filters from first load

**Related Issues**
- N/A

**PR Type**
- Enhancement

2020-08-06 19:08 UTC, gordonmacqueen-lp requested changes

2020-08-06 19:08 UTC, gordonmacqueen-lp commented on report.php
> +if ($id == 0) {
we should use `XAPI_REPORT_ID_ERROR` instead of `0`

2020-08-07 09:58 UTC, lzabo approved these changes

2020-08-07 10:22 UTC, mlynn-lp approved these changes

2020-08-07 15:37 UTC, gordonmacqueen-lp approved these changes

2020-08-07 15:49 UTC, merged