Yet Logstore Work 2024
davidpesce/moodle-logstore_xapi pull request #861
Opened 2024-12-12 18:01 UTC by milt

**Description**
This PR:
* adds ~100 new events
* makes numerous improvements to existing events
* makes numerous test improvements to reduce boilerplate

**PR Type**
- Fix, Enhancement

2024-12-13 14:44 UTC, davidpesce commented
Hi Milt - first off, thank you for this enormous effort. It looks awesome! It's going to take me a bit of time to review, but I'm curious why the CI was removed from pull requests. Could you re-enable that in this PR?

2024-12-16 15:22 UTC, milt commented
> Hi Milt - first off, thank you for this enormous effort. It looks awesome! It's going to take me a bit of time to review, but I'm curious why the CI was removed from pull requests. Could you re-enable that in this PR?

Hi David! As far as I could tell running CI on every push covers pull requests as well, but I'm happy to turn it back on.

2024-12-18 17:34 UTC, milt commented
We added PHP compatibility and some other minor fixes. The support range is now PHP 8.1 to 8.3 and moodle 4.1 to 4.5.

2025-01-30 21:48 UTC, davidpesce requested changes
This is overall awesome! Thank you so much for contributing! 

Please take a look at the comments and let me know your thoughts.

2025-01-30 21:48 UTC, davidpesce commented on src/loader/moodle_curl_lrs.php
> +        //Old Client Code
Can these comments and debug be removed?

2025-01-30 21:48 UTC, davidpesce commented on src/transformer/events/core/badge_awarded.php
> +                            'en' => 'EDLM Moodle LMS'
Can this be made agnostic? ie "Moodle LMS"

2025-01-30 21:48 UTC, davidpesce commented on src/transformer/events/core/badge_awarded.php
> +                            'en' => 'EDLM Moodle LMS'
It's all over, so maybe a global search and replace is better.

2025-01-30 21:48 UTC, davidpesce commented on src/transformer/utils/get_activity/certificate.php
I'm curious why this was renamed rather than replaced?

2025-02-06 15:31 UTC, milt commented on src/transformer/events/core/badge_awarded.php
> +                            'en' => 'EDLM Moodle LMS'
We actually refactored out the LMS category activity but apparently this file didn't get the memo ;). I'll make sure they all use the same fn. As for the name value I can make it generic, but perhaps we should add config for it?

2025-02-06 15:37 UTC, milt commented on src/transformer/utils/get_activity/certificate.php
This _appears_ to be git trying to be cleverer than it should. We removed the original file after centralizing all course module object generation to a single function. Separately we added this util file for generating objects representing tool_certificate certificates. Since there is so much boiler in between the two files it looks like git sees that as a rename?

2025-02-06 16:12 UTC, davidpesce commented on src/transformer/events/core/badge_awarded.php
> +                            'en' => 'EDLM Moodle LMS'
Hmmm, yeah, an admin setting would be awesome!

2025-02-06 17:28 UTC, milt commented on src/transformer/events/core/badge_awarded.php
> +                            'en' => 'EDLM Moodle LMS'
So on further examination it appears to use the full name from the ur-course if available.  https://github.com/yetanalytics/moodle-logstore_xapi/blob/master/src/transformer/utils/get_activity/site.php#L37-L49
I'm gonna see if the user experience for setting that makes sense, but also make the default "Moodle LMS" and fix those badge handlers.

2025-02-06 17:33 UTC, milt commented on src/transformer/events/core/badge_awarded.php
> +                            'en' => 'EDLM Moodle LMS'
Yep, the UI exposes it in site home settings, so I think we're good:
<img width="819" alt="image" src="https://github.com/user-attachments/assets/426fa72c-9709-42c0-820c-2c7099fbf55c" />

2025-02-06 17:54 UTC, milt commented on src/transformer/events/core/badge_awarded.php
> +                            'en' => 'EDLM Moodle LMS'
OK, this work surfaced an issue with our testing, since Moodle stores information on the hidden course ID 1, we should really be using an ID of 2 for all the actual courses in our test data rather than 1. I'm gonna fix that too.

2025-02-07 14:49 UTC, milt commented on src/transformer/events/core/badge_awarded.php
> +                            'en' => 'EDLM Moodle LMS'
OK! This is under internal review but should be updated on this PR soon https://github.com/yetanalytics/moodle-logstore_xapi/pull/77

2025-02-07 18:05 UTC, milt commented
@cliffcaseyyet noticed that there doesn't seem to be a way to set the statement `$.context.platform` from the UI. It currently derives platform (which we added) from the `source_name` config but I don't think that has UI and seems to be hardcoded in the config. I'm gonna make another PR on our side to add a new config for platform so you can, for instance, disambiguate between multiple peer instances of Moodle.

2025-02-07 18:44 UTC, cliffcaseyyet commented on src/loader/moodle_curl_lrs.php
> +        //Old Client Code
this should be resolved.

2025-02-07 18:53 UTC, milt commented
OK @davidpesce it should be all caught up with our changes now. Let us know if you find anything else.

2025-02-07 22:42 UTC, davidpesce approved these changes

2025-02-10 19:53 UTC, merged