Brianlmerritt kent use php 5.6 or 7
davidpesce/moodle-logstore_xapi pull request #95
Opened 2017-03-02 15:49 UTC by brianlmerritt-kent

The composer.json changes should allow Moodle servers with php 5.5, 5.6 and 7.0 to run this plugin. Fix version issue in composer.json and added travis tests

2017-03-02 16:08 UTC, ryansmith94 commented
Hi @brianlmerritt-kent, thank you for your contribution, I'm pretty happy with this, but could you please link me to some documentation for the version syntax you're using in `1.0.0 as 0.12.0`? I'm not sure what the exact behaviour is of the `as` in there.

2017-03-02 16:10 UTC, ryansmith94 commented
Never mind I've found it https://getcomposer.org/doc/articles/aliases.md#require-inline-alias

2017-03-02 16:12 UTC, ryansmith94 commented
What's the reason for your use of the `as`?

2017-03-02 16:14 UTC, brianlmerritt-kent commented
??Some learninglocker dependencies are asking for 0.12.0, so this avoids necessity of accepting less than stable



________________________________
From: Ryan Smith <notifications@github.com>
Sent: 02 March 2017 16:12
To: xAPI-vle/moodle-logstore_xapi
Cc: Brian Merritt; Mention
Subject: Re: [xAPI-vle/moodle-logstore_xapi] Brianlmerritt kent use php 5.6 or 7 (#95)


What's the reason for your use of the as?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/xAPI-vle/moodle-logstore_xapi/pull/95#issuecomment-283697808>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AUr04MHMlssUOu313j8sKd4jyjDk7moyks5rhupTgaJpZM4MRKJ3>.

2017-03-02 16:14 UTC, ryansmith94 commented
The Learning Locker dependencies

- [Moodle Log Expander](https://github.com/LearningLocker/Moodle-Log-Expander)
- [Moodle to xAPI Translator](https://github.com/LearningLocker/Moodle-xAPI-Translator)
- [xAPI Recipe Emitter](https://github.com/LearningLocker/xAPI-Recipe-Emitter)

2017-03-02 16:16 UTC, brianlmerritt-kent commented
Exactly!


https://github.com/LearningLocker/xAPI-Recipe-Emitter/blob/master/composer.json?



________________________________
From: Ryan Smith <notifications@github.com>
Sent: 02 March 2017 16:14
To: xAPI-vle/moodle-logstore_xapi
Cc: Brian Merritt; Mention
Subject: Re: [xAPI-vle/moodle-logstore_xapi] Brianlmerritt kent use php 5.6 or 7 (#95)


The Learning Locker dependencies

  *   Moodle Log Expander<https://github.com/LearningLocker/Moodle-Log-Expander>
  *   Moodle to xAPI Translator<https://github.com/LearningLocker/Moodle-xAPI-Translator>
  *   xAPI Recipe Emitter<https://github.com/LearningLocker/xAPI-Recipe-Emitter>

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/xAPI-vle/moodle-logstore_xapi/pull/95#issuecomment-283698710>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AUr04CSY0xdlgiVxZmctctyRecUklM0bks5rhur7gaJpZM4MRKJ3>.

2017-03-02 16:19 UTC, ryansmith94 commented
Ok so I think we can apply the same changes from here in the Learning Locker dependencies.

- [composer.json in the Emitter](https://github.com/LearningLocker/xAPI-Recipe-Emitter/blob/master/composer.json#L15)
- [travis.yml in the Emitter](https://github.com/LearningLocker/xAPI-Recipe-Emitter/blob/master/.travis.yml#L2)
- [travis.yml in the Translator](https://github.com/LearningLocker/Moodle-xAPI-Translator/blob/master/.travis.yml#L2)
- [travis.yml in the Expander](https://github.com/LearningLocker/Moodle-Log-Expander/blob/master/.travis.yml#L2)

Obviously the composer.lock file will also need to change in the Emitter.

2017-03-02 16:19 UTC, ryansmith94 commented
Once those changes have been made we can just use 1.0.0 and drop the use of `as` which is definitely preferred.

2017-03-02 16:28 UTC, brianlmerritt-kent commented
?Yes, agreed

________________________________
From: Ryan Smith <notifications@github.com>
Sent: 02 March 2017 16:19
To: xAPI-vle/moodle-logstore_xapi
Cc: Brian Merritt; Mention
Subject: Re: [xAPI-vle/moodle-logstore_xapi] Brianlmerritt kent use php 5.6 or 7 (#95)


Once those changes have been made we can just use 1.0.0 and drop the use of as which is definitely preferred.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/xAPI-vle/moodle-logstore_xapi/pull/95#issuecomment-283700118>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AUr04NmD8OowThV9JDzo7f8ldPVXVpW3ks5rhuwQgaJpZM4MRKJ3>.

2017-05-15 15:39 UTC, davidpesce commented
Added necessary changes to dependencies (Emitter, Translator, and Expander)

- Translator - https://github.com/LearningLocker/Moodle-xAPI-Translator/pull/52
- Expander - https://github.com/LearningLocker/Moodle-Log-Expander/pull/44
- Emitter - https://github.com/LearningLocker/xAPI-Recipe-Emitter/pull/37

2017-05-16 15:32 UTC, davidpesce commented
@ryansmith94 is this one approved for merge?

2017-05-16 15:35 UTC, ryasmi requested changes

2017-05-16 15:35 UTC, ryansmith94 commented on composer.json
> +        "rusticisoftware/tincan": "1.0.0 as 0.12.0",
Can we change this to just be 1.0.0 @davidpesce?

2017-05-16 15:39 UTC, davidpesce commented on composer.json
> +        "rusticisoftware/tincan": "1.0.0 as 0.12.0",
Should be all set!

2017-05-16 15:40 UTC, ryasmi approved these changes

2017-05-16 15:49 UTC, merged